### ISSUE TITLE
Custom view width i showing incorrectly.

### ISSUE THREAD

**Issue by nandinicbit1981** [florent37/ViewTooltip#15]
Is the width being set to a specific value? I see that the tooltip is having a specific width and wrapping all the text , the width is about 10% of the screen and tooltip overflows in height.

**Comment by krisnamargono** [comment]
hello @nandinicbit1981 do you have any progress about your current problem? Because I want to set max width to my custom view and it's not working

**Comment by nierongcheng** [comment]
@nandinicbit1981 which library do you use?

**Comment by nandinicbit1981** [comment]
@nierongcheng Sorry, i meant i ended up writing my own ViewToolTip class using the current tooltip class as a reference, to match my app's requirements. I wrote some custom functions to specifically meet my app's requirements.

**Comment by florent37** [comment]
can you try the 1.1.2 ?
