### ISSUE TITLE
It doesn't work in case of DialogFragment

### ISSUE THREAD

**Issue by KalpeshDesai** [florent37/ViewTooltip#17]
If i use ViewTooltip from a dialog fragment then it doesn't work and shows behind the dialog.

I used following code to show tooltip.
        ViewTooltip.on(button)
                .position(ViewTooltip.Position.BOTTOM)
                .color(Color.GRAY)
                .corner(30)
                .textSize(TypedValue.COMPLEX_UNIT_DIP, 18)
                .text(tooltip)
                .clickToHide(true)
                .autoHide(true, 3000)
                .animation(new ViewTooltip.FadeTooltipAnimation(500))
                .show();

Am i missing something to show it on top of the dialog?

Thanks,
Kalpesh

**Comment by florent37** [comment]
the the 1.1.1, and une .on(/*FRAGMENT*/ this, button)
