### ISSUE TITLE
Tooltip is cropped for long text

### ISSUE THREAD

**Issue by johnaziz57** [florent37/ViewTooltip#18]
As shown here when tool tip text is very big the tool tip is cropped from right, tested on API 18 and API 24
![screenshot_1505059168](https://user-images.githubusercontent.com/14923445/30250626-f26447f4-9651-11e7-926d-9e71e8c92a4e.png)

it is even more noticeable when Align is set to `START`
![screenshot_20170910-190936](https://user-images.githubusercontent.com/14923445/30251235-e9f1b76e-965b-11e7-967a-d5b2e3ae9047.png)

**Comment by auf1r2** [comment]
I suppose this lib is not intended to show too much text.

**Comment by khalid-mahmood** [comment]
same problem.. and \n is not working.
getting text from xml string resources

**Comment by florent37** [comment]
will try to fix it today

**Comment by florent37** [comment]
you can try the 1.1.2 👍

**Comment by florent37** [comment]
![device-2018-01-11-140009](https://user-images.githubusercontent.com/5754972/34826859-7ea5394e-f6d8-11e7-8745-f6ff06b344a2.png)

**Comment by khalid-mahmood** [comment]
Thanks.. :)

**Comment by khalid-mahmood** [comment]
@florent37 😢 
Now problem with left side Tooltips
![device-2018-01-12-094643](https://user-images.githubusercontent.com/6528169/34860187-a87c95aa-f77d-11e7-8291-98f616550d84.png)
