### ISSUE TITLE
Two error

### ISSUE THREAD

**Issue by RealFeeling** [florent37/ViewTooltip#2]
1. can't on toolbar

2. on fabButton , show position is wrong

**Comment by florent37** [comment]
can you send me screens ?

**Comment by RealFeeling** [comment]
if (CUtils.getSharedPreference().getBoolean(INTRO_ADD_BOOKBUTTON, false)) {
            ViewTooltip.on(fabCreateBook)
                    .position(ViewTooltip.Position.LEFT)
                    .align(ViewTooltip.ALIGN.CENTER)
                    .autoHide(true, 3000)
                    .text(getString(R.string.hint_add_book_button))
                    .clickToHide(true)
                    .show();
            CUtils.getSharedPreference().edit().putBoolean(INTRO_ADD_BOOKBUTTON, true).apply();
        }

 <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab_create_book"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right|bottom"
        android:layout_marginEnd="35dp"
        android:layout_marginBottom="35dp"
        android:src="@drawable/ic_book_add"
        android:stateListAnimator="@drawable/lift_on_touch"
        app:backgroundTint="@color/colorRoot_light"
        app:elevation="6dp"
        app:pressedTranslationZ="12dp"
        app:rippleColor="#33728dff"
        />

![image](https://user-images.githubusercontent.com/12228071/27071434-8810a5a2-504f-11e7-9bed-1903f728a322.png)
