### ISSUE TITLE
Centered Tooltip with long text doesn't stay in screen limits

### ISSUE THREAD

**Issue by Gaetano-Dati** [florent37/ViewTooltip#25]
I have a so long text to show in the Tooltip and, unfortunately, It goes out of the screen. Maybe It needs some developer work to rebuild once a limit gets reached. It would make this beautiful library more useful. Thanks

**Comment by KennyGoers** [comment]
Any thoughts on this? For a quick hack force smaller than the screen width by X?

**Comment by KennyGoers** [comment]
So not fixed?

**Comment by Gaetano-Dati** [comment]
No, as it seems
