### ISSUE TITLE
Content going outside the screen bounds

### ISSUE THREAD

**Issue by akashpathak** [florent37/ViewTooltip#3]
Hi,
Is there a way to wrap the content such that the tooltip will encompass the entire text. Here is the problem I am facing:
ViewTooltip
                    .on(v)
                    .align(CENTER)
                    .position(ViewTooltip.Position.LEFT)
                    .text("Some tooltip with long text. What happens if this is really really long. Because the description of a category might go long. " + "What would happen to this sentence.")
                    .clickToHide(true)
                    .autoHide(false, 0)
                    .show();

![screenshot](https://user-images.githubusercontent.com/11562530/27087082-071e2c9e-5022-11e7-9c80-da1b1ff38eeb.jpeg)

**Comment by florent37** [comment]
ok, will check

**Comment by florent37** [comment]
I fixed this in 1.0.3, can you check ?

**Comment by akashpathak** [comment]
Works very well. Thanks 👍

**Comment by jimmy-jose** [comment]
Hi @florent37 ,
If the position is TOP or BOTTOM, the text stays inside but part of the bubble is still going out of the screen. 
![viewtooltipbug](https://user-images.githubusercontent.com/20584190/34192178-6e16bc3c-e572-11e7-8b8b-844289b5904c.png)

Awesome work btw :)
