### ISSUE TITLE
Any way to create tooltips without arrows?

### ISSUE THREAD

**Issue by prscX** [florent37/ViewTooltip#31]
Hi @florent37,

Is their any API through which we can remove or specify height/width of arrows?

Thanks
Pranav

**Comment by florent37** [comment]
Not yet but i Can implément this

**Comment by prscX** [comment]
Thanks a lot @florent37 for considering our request.

Please let me know in case any help needed from my end.

Thanks 
Pranav

**Comment by florent37** [comment]
hi, can you try the 1.1.4 please ? 
play with .setArrowWidth & .setArrowHeight

**Comment by prscX** [comment]
Many Thanks @florent37 for taking this on priority and staying on top of this.

I will validate the same from my end and will share the results.

Thanks
Pranav

**Comment by prscX** [comment]
Thanks @florent37. It is working as expected. Please find below screenshot of tooltip without arrow:

<img width="161" alt="screen shot 2018-03-08 at 6 01 26 am" src="https://user-images.githubusercontent.com/28862892/37126273-478e38b8-2296-11e8-9634-2dbbc9a41c37.png">

Is it possible to have padding/margin between button and tooltip? I have tried padding using below snippet but not sure why it is not working, maybe I am missing something. Can you please help me with this:

`tooltip = tooltip.padding(100, 100, 100, 100);`

Thanks
Pranav

**Comment by florent37** [comment]
I will try to add an attribute "margin" today

**Comment by florent37** [comment]
you can use `1.1.5` for this fix and the method `.distanceWithView(0)`

tested ;)

**Comment by prscX** [comment]
Many thanks @florent37 for adding API in order to provide distance between view and tooltip.

Thanks 
Pranav
