### ISSUE TITLE
can i change the backgroud？

### ISSUE THREAD

**Issue by SheepYang1993** [florent37/ViewTooltip#4]

**Comment by florent37** [comment]
You can use .color(your color)

You wanted a custom drawable background ?

**Comment by SheepYang1993** [comment]
@florent37 how to set a custom drawable?9patch drawable?

**Comment by florent37** [comment]
Not possible yet, but I will do that ;)

**Comment by MalcolmMcFly** [comment]
.color() is still not working for me:

`mTimeToolTip
                .on(mStartTime)
                .clickToHide(true)
                .autoHide(false, 1000)
                .corner(30)
                .color(ContextCompat.getColor(mContext, R.color.datecart))
                .position(ViewTooltip.Position.TOP)
                .text("Chose a time for your date, \nwe'll also show you the weather")
                .show();`

**Comment by florent37** [comment]
oh I see, I forgot to use paint.setColor on my shape :/

**Comment by MalcolmMcFly** [comment]
@SheepYang1993 if you can't wait, download ViewTooltip.java and change the color on line 193: `        private int color = Color.parseColor("#3F51B5");
`

**Comment by florent37** [comment]
sorry for the delay, I'm working on it right now ;)

**Comment by florent37** [comment]
done, check the 1.0.4 ;)
