### ISSUE TITLE
Tooltip not being clipped for Position.TOP

### ISSUE THREAD

**Issue by MalcolmMcFly** [florent37/ViewTooltip#6]
mTimeToolTip
            .on(mStartTime)
            .clickToHide(true)
            .autoHide(false, 1000)
            .corner(30)
            .color(ContextCompat.getColor(mContext, R.color.datecart))
            .position(ViewTooltip.Position.TOP)
            .text("Chose a time for your date, \nwe'll also show you the weather")
            .show();
![clipping_error](https://user-images.githubusercontent.com/15109016/27215042-b8f11138-5299-11e7-9e38-29a9aada5d61.png)

**Comment by florent37** [comment]
Oh yes, I forgot this

2017-06-16 8:43 GMT+02:00 Maloclm McFly <notifications@github.com>:

**Comment by florent37** [comment]
It need some time to be refactored, can you try to use .right before I do that ? please

**Comment by AlirezaGhanbarinia** [comment]
hi,
i have the same issue.
and another question, is it possible to move " img arrow down " to right or left or center of a view and also set margin for that?

![untitled](https://user-images.githubusercontent.com/15226836/27368994-fa76de88-566a-11e7-91aa-333e993c034d.png)

**Comment by florent37** [comment]
can you try on a new version ?
1.0.6 ?

**Comment by AlirezaGhanbarinia** [comment]
thank you
the alignment problem  is fixed 

but the other problem is not fixed yet. i mean the position of "img arrow down".
i have attached 2 images below to clear the problem. the second image is the thing we need to be implemented.

![first](https://user-images.githubusercontent.com/15226836/27768297-b86761bc-5f24-11e7-84aa-488111d26f26.png)

![download2](https://user-images.githubusercontent.com/15226836/27768323-9457be42-5f25-11e7-8c65-3cbe2ee970c4.png)

**Comment by ivandiazmolina** [comment]
But the text is not center vertically :(, if you see the picture, left and right margins its OK but margin bottom is 0.

https://user-images.githubusercontent.com/15226836/27768297-b86761bc-5f24-11e7-84aa-488111d26f26.png

**Comment by florent37** [comment]
you can use .padding(int, int) ;)
